# Generated by Django 2.2.9 on 2020-03-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_image', models.ImageField(upload_to='owner_image')),
                ('store_image', models.ImageField(upload_to='store_image')),
                ('store_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('registered_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
