# Generated by Django 2.2.9 on 2020-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image'),
        ),
    ]
