# Generated by Django 2.2.9 on 2020-03-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200308_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_image',
        ),
    ]
