# Generated by Django 2.2.9 on 2020-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=400)),
                ('product_image1', models.ImageField(blank=True, upload_to='product_image')),
                ('product_image2', models.ImageField(blank=True, upload_to='product_image')),
                ('product_image3', models.ImageField(blank=True, upload_to='product_image')),
                ('product_image4', models.ImageField(blank=True, upload_to='product_image')),
            ],
        ),
    ]
